GestaoProfissionais/Models/Especialidade.cs
namespace GestaoProfissionais.Models
{
    public class Especialidade
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string TipoDocumento { get; set; }
    }
}

GestaoProfissionais/Models/Profissional.cs
namespace GestaoProfissionais.Models
{
    public class Profissional
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Especialidade { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
    }
    public class ProfissionaisViewModel
    {
        public List<Profissional> Profissionais { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
        public int PageSize { get; set; }
    }
}

GestaoProfissionais/Controllers/HomeController.cs
using GestaoProfissionais.Data;
using GestaoProfissionais.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

public class HomeController : Controller
{
    private readonly ApplicationDbContext _context;

    public HomeController(ApplicationDbContext context)
    {
        _context = context;
    }
    public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 10, string mensagemTipo = null, string mensagemTexto = null)
     {
        ViewBag.Especialidades = await _context.Especialidades.ToListAsync();
        ViewBag.MensagemTipo = mensagemTipo;
        ViewBag.MensagemTexto = mensagemTexto;
        var totalProfissionais = await _context.Profissionais.CountAsync();

        var totalPages = (int)Math.Ceiling(totalProfissionais / (double)pageSize);

        var profissionais = await _context.Profissionais
            .Skip((pageNumber - 1) * pageSize)
            .Take(pageSize)
            .ToListAsync();

        ViewData["CurrentPage"] = pageNumber;
        ViewData["TotalPages"] = totalPages;
        ViewData["PageSize"] = pageSize;

        return View("~/Views/Index.cshtml",profissionais);
    }

    public async Task<IActionResult> Edit(int id)
    {
        var profissional = await _context.Profissionais.FindAsync(id);
        if (profissional == null) return NotFound();

        return View(profissional);
    }

    [HttpPost("Edit")]
    public async Task<IActionResult> Edit(int Id, string Nome, string Especialidade, string TipoDocumento, string NumeroDocumento)
    {
        var profissionalExistente = await _context.Profissionais.FindAsync(Id);
        string mensagemTipo;
        string mensagemTexto;
        if (profissionalExistente != null)
        {
            profissionalExistente.Nome = Nome;
            profissionalExistente.Especialidade = Especialidade;
            profissionalExistente.TipoDocumento = TipoDocumento;
            profissionalExistente.NumeroDocumento = NumeroDocumento;

            await _context.SaveChangesAsync();
            mensagemTipo = "sucess";
            mensagemTexto = "Profissional editado com sucesso!";
        } else
        {
            mensagemTipo = "danger";
            mensagemTexto = "Erro ao editar profissional.";
        }
        return RedirectToAction(nameof(Index), new { mensagemTipo, mensagemTexto });
    }

    [HttpPost]
    public async Task<IActionResult> Delete(int id)
    {
        var profissional = await _context.Profissionais.FindAsync(id);
        string mensagemTipo;
        string mensagemTexto;

        if (profissional != null)
        {
            _context.Profissionais.Remove(profissional);
            await _context.SaveChangesAsync();
            mensagemTipo = "success";
            mensagemTexto = "Profissional excluído com sucesso!";
        }
        else
        {
            mensagemTipo = "danger";
            mensagemTexto = "Erro ao excluir profissional.";
        }
        return RedirectToAction(nameof(Index), new { mensagemTipo, mensagemTexto });
    }
}

GestaoProfissionais/Controllers/ProfissionaisController.cs
using GestaoProfissionais.Data;
using GestaoProfissionais.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GestaoProfissionais.Controllers
{
    [Route("Profissional")]
    public class ProfissionaisController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProfissionaisController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpPost("Create")]
        public IActionResult Create([FromBody] Profissional profissional)
        {
            if (ModelState.IsValid)
            {
                _context.Add(profissional);
                _context.SaveChanges();
                return Ok();
            }
            return BadRequest();
        }

        [HttpGet("GetEspecialidades")]
        public IActionResult GetEspecialidades()
        {
            var especialidades = _context.Especialidades
                            .Select(s => new { s.Id, s.Nome, s.TipoDocumento })
                            .ToList();
                        return Json(especialidades);
        }
    }
}

GestaoProfissionais/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GestaoProfissionais.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

GestaoProfissionais/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestão de Profissionais</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestaoProfissionais.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="d-flex justify-content-between align-items-center mb-4">
                    <a class="navbar-brand" asp-area="" asp-page="/Index"><h1 class="h4">Gestão de Profissionais</h1></a>
                    <i class="bi bi-people"></i>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GestaoProfissionais/Views/Index.cshtml
@model IEnumerable<GestaoProfissionais.Models.Profissional>
@{
    ViewData["Title"] = "Gestão de Profissionais";
}

<body>
    <div class="container mt-4">
        @* Cabeçalho *@
        <div class="d-flex justify-content-between align-items-center header">
            <h1 class="h4">Gestão de Profissionais</h1>
            <i class="bi bi-people fs-3"></i>
        </div>
        @* Botões filtro e adicionar *@
        <div class="d-flex justify-content-between align-items-center mt-4">
            <select id="filtroEspecialidade" class="form-select mt-3" onchange="filtrar()">
                <option value="">Filtrar por: Todos</option>
                @foreach (var especialidade in ViewBag.Especialidades)
                {
                    <option value="@especialidade.Nome">Filtrar por: @especialidade.Nome</option>
                }
            </select>
            <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#modalAdd" href="@Url.Action("Create", "Profissionais")">
                Adicionar +</button>
        </div>

        @* Modal Adicionar *@
        <div class="modal fade" id="modalAdd" tabindex="-1" aria-labelledby="modalAddLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modalAddLabel">Adicionar Profissional</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
                    </div>
                    <div class="modal-body">
                        <form id="formAddProfissional">
                            <div class="mb-3">
                                <label for="nome" class="form-label">Nome do Profissional</label>
                                <input type="text" class="form-control" id="nome" name="nome" required>
                            </div>
                            <div class="mb-3">
                                <label for="especialidade" class="form-label">Especialidade</label>
                                <select class="form-select" id="especialidade" name="especialidade" required>
                                    <option value="" selected disabled>Selecione uma especialidade</option>
                                </select>
                            </div>
                            <div class="mb-3">
                                <label for="tipoDocumento" class="form-label">Tipo do Documento</label>
                                <input type="text" class="form-control" id="tipoDocumento" name="tipoDocumento" readonly>
                            </div>
                            <div class="mb-3">
                                <label for="numeroDocumento" class="form-label">Número do Documento</label>
                                <input type="text" class="form-control" id="numeroDocumento" name="numeroDocumento" required>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button type="button" class="btn btn-success" id="btnSalvarProfissional">Salvar</button>
                    </div>
                </div>
            </div>
        </div>

        @* Tabela *@
        <div class="mt-3">
            <table class="table table-responsive table-bordered table-hover text-center">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nome</th>
                        <th scope="col">Especialidade</th>
                        <th scope="col">Tipo do Documento</th>
                        <th scope="col">Número do documento</th>
                        <th scope="col">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        @foreach (var profissional in Model)
                        {
                            <tr>
                                <td scope="row">@profissional.Id</td>
                                <td>@profissional.Nome</td>
                                <td>@profissional.Especialidade</td>
                                <td>@profissional.TipoDocumento</td>
                                <td>@profissional.NumeroDocumento</td>
                                <td>
                                    @* <i class="bi bi-three-dots" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false"></i> *@
                                    <button class="btn btn-warning btn-edit" data-bs-toggle="modal" data-bs-target="#modalEditar-@profissional.Id"
                                            data-id="@profissional.Id" data-nome="@profissional.Nome" data-especialidade="@profissional.Especialidade"
                                            data-tipoDocumento="@profissional.TipoDocumento" data-numeroDocumento="@profissional.NumeroDocumento">
                                        Editar
                                    </button>
                                    <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modalExcluir" data-id="@profissional.Id">Excluir</button>
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="6" class="text-center">Nenhum profissional encontrado.</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        @* Modal Editar *@
        @foreach (var profissional in Model)
        {

            <div class="modal fade" id="modalEditar-@profissional.Id" tabindex="-1" aria-labelledby="modalEditarLabel-@profissional.Id" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="modalEditarLabel-@profissional.Id">Editar Profissional</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
                        </div>
                        <div class="modal-body">
                            <form id="formEditarProfissional" method="post" action="@Url.Action("Edit", "Home")">
                                <input type="hidden" name="Id" value="@profissional.Id" />
                                <div class="mb-3">
                                    <label for="nome" class="form-label">Nome do Profissional</label>
                                    <input type="text" class="form-control" id="nome" name="nome" value="@profissional.Nome" />
                                </div>
                                <div class="mb-3">
                                    <label for="especialidade" class="form-label">Especialidade</label>
                                    @* <select class="form-select" id="especialidade" name="especialidade" required>
                                        <option value="">Selecione uma especialidade</option>
                                        @foreach (var especialidade in ViewBag.Especialidades as List<GestaoProfissionais.Models.Especialidade>)
                                        {
                                            <option value="@especialidade.Nome" selected="@((especialidade.Nome == profissional.Especialidade) ? "selected" : "")">
                                                @especialidade.Nome
                                            </option>
                                        }
                                    </select> *@
                                    <input type="text" class="form-control" id="especialidade" name="especialidade" value="@profissional.Especialidade" readonly />
                                </div>
                                <div class="mb-3">
                                    <label for="tipoDocumento" class="form-label">Tipo do Documento</label>
                                    <input type="text" class="form-control" id="tipoDocumento" name="tipoDocumento" value="@profissional.TipoDocumento" readonly/>
                                </div>
                                <div class="mb-3">
                                    <label for="numeroDocumento" class="form-label">Número do Documento</label>
                                    <input type="text" class="form-control" id="numeroDocumento" name="numeroDocumento" value="@profissional.NumeroDocumento" />
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                    <button type="submit" class="btn btn-success">Salvar</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        }

        @* Modal confirma exclusão *@
        <div class="modal fade" id="modalExcluir" tabindex="-1" aria-labelledby="modalExcluirLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modalExcluirLabel">Excluir Profissional</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
                    </div>
                    <div class="modal-body">
                        Tem certeza que deseja excluir este profissional? Essa ação não poderá ser desfeita!
                        <br />
                        <div style="display: flex; justify-content: center; align-items: center; margin-top: 10px;">
                            <img id="loadingSpinner" src="https://i.gifer.com/VAyR.gif" alt="Carregando..." style="display: none; width: 30px; height: 30px;" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <form id="deleteForm" method="post" action="">
                            <input type="hidden" name="id" id="deleteId">
                            <button type="submit" class="btn btn-danger" id="deleteButton">Sim, excluir</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        @* Alerts *@
        @if (!string.IsNullOrEmpty(ViewBag.MensagemTexto))
        {
            <div class="alert alert-@ViewBag.MensagemTipo" role="alert">
                @ViewBag.MensagemTexto
            </div>
        }

        @* Paginação *@
        <nav>
            <ul class="pagination justify-content-center">
                @if (ViewData["CurrentPage"] != null && (int)ViewData["CurrentPage"] > 1)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", new { pageNumber = (int)ViewData["CurrentPage"] - 1, pageSize = (int)ViewData["PageSize"] })">&lt;</a>
                    </li>
                }
                else
                {
                    <li class="page-item disabled">
                        <a class="page-link" href="#"> &lt; </a>
                    </li>
                }

                @for (int i = 1; i <= (int)(ViewData["TotalPages"] ?? 1); i++) 
                {
                    <li class="page-item @(i == (int)(ViewData["CurrentPage"] ?? 1) ? "active" : "")">
                        <a class="page-link" href="@Url.Action("Index", new { pageNumber = i, pageSize = (int)(ViewData["PageSize"] ?? 10) })">@i</a>
                    </li>
                }

                @if (ViewData["CurrentPage"] != null && (int)ViewData["CurrentPage"] < (int)(ViewData["TotalPages"] ?? 1))
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", new { pageNumber = (int)ViewData["CurrentPage"] + 1, pageSize = (int)(ViewData["PageSize"] ?? 10) })">&gt;</a>
                    </li>
                }
                else
                {
                    <li class="page-item disabled">
                        <a class="page-link" href="#"> &gt; </a>
                    </li>
                }
            </ul>
        </nav>
    </div>
</body>

GestaoProfissionais/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestão de Profissionais</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestaoProfissionais.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>